image:
  repository: debian
  tag: stable-slim

schedule: "*/1 * * * *"
command: ""
shell: "/bin/sh"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 999

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

secret:
  enabled: false

constraints:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
