{{- define "common.pvc.tpl" -}}
{{- range .Values.volumes }}
{{- if not or (.existingClaim .configMap) }}
{{- $robustName := include "common.robustName" $.Release.Name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" $robustName .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteOnce" }}
  {{- if .storageClass }}
  storageClassName: {{ .storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size | default "1Gi" }}
{{- end }}
{{- end }}
{{- end -}}
